// <auto-generated />
using CobblemonMarketApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CobblemonMarketApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307172748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CobblemonMarketApi.Models.ItemListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemListings");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.PokemonListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttackIv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefenseIv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HpIv")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShiny")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PokedexNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PokemonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialAttackIv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialDefenseIv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeedIv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalIvPercentage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PokemonListings");
                });
#pragma warning restore 612, 618
        }
    }
}
