// <auto-generated />
using System;
using CobblemonMarketApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CobblemonMarketApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310120016_AddPokemonListingUuidAndForm")]
    partial class AddPokemonListingUuidAndForm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CobblemonMarketApi.Models.AbilityCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AbilityCatalog");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.ItemListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemListings");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.PokemonAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbilityCatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokedexNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbilityCatalogId");

                    b.HasIndex("PokedexNumber", "AbilityCatalogId", "IsHidden", "Slot");

                    b.ToTable("PokemonAbilities");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.PokemonCatalog", b =>
                {
                    b.Property<int>("PokedexNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FrenchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PokedexNumber");

                    b.HasIndex("EnglishName");

                    b.HasIndex("FrenchName");

                    b.ToTable("PokemonCatalog");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.PokemonListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttackIv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefenseIv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Form")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HpIv")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShiny")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PokedexNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PokemonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialAttackIv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialDefenseIv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeedIv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalIvPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasFilter("\"Uuid\" <> ''");

                    b.ToTable("PokemonListings");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.Showcase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Showcases");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.ShowcaseItemListing", b =>
                {
                    b.Property<int>("ShowcaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemListingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShowcaseId", "ItemListingId");

                    b.HasIndex("ItemListingId");

                    b.ToTable("ShowcaseItemListings");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.ShowcasePokemonListing", b =>
                {
                    b.Property<int>("ShowcaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonListingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShowcaseId", "PokemonListingId");

                    b.HasIndex("PokemonListingId");

                    b.ToTable("ShowcasePokemonListings");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.PokemonAbility", b =>
                {
                    b.HasOne("CobblemonMarketApi.Models.AbilityCatalog", "AbilityCatalog")
                        .WithMany("PokemonAbilities")
                        .HasForeignKey("AbilityCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CobblemonMarketApi.Models.PokemonCatalog", "PokemonCatalog")
                        .WithMany("PokemonAbilities")
                        .HasForeignKey("PokedexNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbilityCatalog");

                    b.Navigation("PokemonCatalog");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.ShowcaseItemListing", b =>
                {
                    b.HasOne("CobblemonMarketApi.Models.ItemListing", "ItemListing")
                        .WithMany("ShowcaseLinks")
                        .HasForeignKey("ItemListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CobblemonMarketApi.Models.Showcase", "Showcase")
                        .WithMany("ItemListingLinks")
                        .HasForeignKey("ShowcaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemListing");

                    b.Navigation("Showcase");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.ShowcasePokemonListing", b =>
                {
                    b.HasOne("CobblemonMarketApi.Models.PokemonListing", "PokemonListing")
                        .WithMany("ShowcaseLinks")
                        .HasForeignKey("PokemonListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CobblemonMarketApi.Models.Showcase", "Showcase")
                        .WithMany("PokemonListingLinks")
                        .HasForeignKey("ShowcaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PokemonListing");

                    b.Navigation("Showcase");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.AbilityCatalog", b =>
                {
                    b.Navigation("PokemonAbilities");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.ItemListing", b =>
                {
                    b.Navigation("ShowcaseLinks");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.PokemonCatalog", b =>
                {
                    b.Navigation("PokemonAbilities");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.PokemonListing", b =>
                {
                    b.Navigation("ShowcaseLinks");
                });

            modelBuilder.Entity("CobblemonMarketApi.Models.Showcase", b =>
                {
                    b.Navigation("ItemListingLinks");

                    b.Navigation("PokemonListingLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
