<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="obj\**\*.cs" />
    <Compile Remove="build-check\**\*.cs" />
    <Compile Remove="build-check-form\**\*.cs" />
    <Compile Remove="build-check-ivfix\**\*.cs" />
    <Compile Remove="artifacts\**\*.cs" />
    <Compile Remove="CobblemonMarketApi.Tests\**\*.cs" />
    <Content Remove="CobblemonMarketApi.Tests\**\*" />
    <EmbeddedResource Remove="CobblemonMarketApi.Tests\**\*" />
    <None Remove="CobblemonMarketApi.Tests\**\*" />
  </ItemGroup>

</Project>
